
CORPUS_FILE_PATH = "./data/vectors.bin.skipgram.mergenew.2.3"
DATA_SET_PATH = "./data/data.txt"
TRAIN_SET_PATH = "./data/train/train.txt"
TEST_SET_PATH = "./data/test/test.txt"
TOKEN_REPRESENTATION_SIZE = 200
INPUT_SEQUENCE_LENGTH = 20
ANSWER_MAX_TOKEN_LENGTH = 20
VOCAB_MAX_SIZE = 20000
HIDDEN_LAYER_DIMENSION = 512
FULL_LEARN_ITER_NUM = 100
SAMPLES_BATCH_SIZE = 5000
EOS_SYMBOL = '$'
EMPTY_SYMBOL= '#'
TRAIN_BATCH_SIZE = 200 
NN_MODEL_PATH = './model/model'
