
CORPUS_FILE_PATH = "./data/vectors.bin.skipgram.mergenew.2.3"
DATA_SET_PATH = "./data/data.txt"
TRAIN_SET_PATH = "./data/train/train.txt"
TEST_SET_PATH = "./data/test/test.txt"
TOKEN_REPRESENTATION_SIZE = 300
INPUT_SEQUENCE_LENGTH = 20
ANSWER_MAX_TOKEN_LENGTH = 16
VOCAB_MAX_SIZE = 20000
HIDDEN_LAYER_DIMENSION = 512
FULL_LEARN_ITER_NUM = 500
SAMPLES_BATCH_SIZE = 100
EOS_SYMBOL = '$$$'
EMPTY_SYMBOL= '###'
TRAIN_BATCH_SIZE = 20 
NN_MODEL_PATH = './model/model'
